name: Deploy nginx to ec2
on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload nginx.conf to S3
        run: aws s3 cp nginx.conf s3://homework-1212/nginx/nginx.conf

      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Update nginx config" \
            --parameters 'commands=[
              "echo Updating nginx config...",
              "aws s3 cp s3://homework-1212/nginx/nginx.conf /etc/nginx/sites-available/default",
              "echo Done.."
            ]'
